services:
  nvim:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - socks_proxy=${socks_proxy}
        - USERNAME=`whoami`
        - USERID=`id -u`
        - GROUPID=`id -g`
    network_mode: host
    volumes:
      - ${HOME}:${HOME}
